### ISSUE TITLE
python3.8?

### ISSUE THREAD

**Issue by Billybangleballs** [Dragon863/EchoCLI#2]
python3.7 throws error, is it python3.8 code?

`[19:22:55] INFO: Please short the device as shown in the image at https://dragon863.github.io/blog/mainboard.jpg`
`[19:22:55] INFO: To open the device, you will need a torx 8 screwdriver.`
`Traceback (most recent call last):`
`  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main`
`    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)`
`  File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details`
`    return _get_module_details(pkg_main_name, error)`
`  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details`
`    __import__(pkg_name)`
`  File "/home/bb/EchoCLI-main/internal/amonet/amonet/__init__.py", line 247`
`    while chunk := f.read(8192):`
`                 ^`
`SyntaxError: invalid syntax`
`Select an option: >`

**Comment by Dragon863** [comment]
Yes, sorry I wasn't aware that the operator is not implemented in python 3.7 and below. If you need I can rewrite the section for 3.8 when I get a chance, but if you have access to 3.8 it should work fine

**Comment by Billybangleballs** [comment]
Thanks for the clarification.
I shall use a different computer with 3.8 and see how I get on.
