### ISSUE TITLE
RuntimeError: read fail

### ISSUE THREAD

**Issue by LiquidSchwartz** [Dragon863/EchoCLI#20]
[22:59:46] Init crypto engine
[22:59:46] Disable caches
[22:59:46] Disable bootrom range checks
[22:59:46] Load payload from brom-payload/build/payload.bin = 0x45C0 bytes
[22:59:46] Send payload
[22:59:46] Let's rock
[22:59:46] Wait for the payload to come online...
[22:59:47] all good
[22:59:47] Check GPT
Traceback (most recent call last):
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\myusername\Downloads\EchoCLI-main\EchoCLI-main\internal\amonet\amonet\__main__.py", line 3, in <module>
    amonet.main()
  File "C:\Users\myusername\Downloads\EchoCLI-main\EchoCLI-main\internal\amonet\amonet\__init__.py", line 219, in main
    switch_user(dev)
  File "C:\Users\myusername\Downloads\EchoCLI-main\EchoCLI-main\internal\amonet\amonet\__init__.py", line 131, in switch_user
    block = dev.emmc_read(0)
  File "C:\Users\myusername\Downloads\EchoCLI-main\EchoCLI-main\internal\amonet\amonet\common.py", line 180, in emmc_read
    raise RuntimeError("read fail")
RuntimeError: read fail

**Comment by Dragon863** [comment]
Have you definitely shorted the pins correctly?

**Comment by LiquidSchwartz** [comment]
Yes I ended up using my Linux and it worked, I am in the mainframe, is there any way to get my own tts running? I see tinyplay but whenever I play an audio file it makes the speakers go wacky, also is there any way to patch it to make it so I dont need to run  that command every time, my goal with this is to disable the actual echo script and program my own virtual assistant which will run on the echo.

**Comment by Dragon863** [comment]
Most of your questions are things I'd like to figure out too, but I don't have a solution for many at the moment. I'm currently very busy with exams, but I do hope to continue with this project at some point. I will close this issue as you have resolved the main problem

**Comment by LiquidSchwartz** [comment]
@Dragon863 Just wondering do u think its possible to install a custom linux distro onto the alexa so we dont need to run the mtkclient each time. And so we can run custom code and install nodejs etc

**Comment by LiquidSchwartz** [comment]
@Dragon863 I accidentally renamed "system" to a folder called "system2" now i cant access adb shell or anything

**Comment by Dragon863** [comment]
For your first question, there is a port of postmarketos available, but that won't remove the requirement for a tethered boot of course, the reason we use mtkclient is that once the echo has been modified, it is no longer signed by Amazon and so refuses to boot securely.
For your second question, follow the readme's "bricked your echo?" section

**Comment by LiquidSchwartz** [comment]
I flashed a backup but that didnt restore filesystem, I will try the bricked your echo section I hope that recreates the file system

**Comment by LiquidSchwartz** [comment]
And as for the postmarketos, how do I go about flashing that @Dragon863

**Comment by KowalskiStan** [comment]
I'm not sure the brick thing will help as I don't think it will completely wipe the echo and remake the /system/, but I hope it will

**Comment by LiquidSchwartz** [comment]
@Dragon863 It worked, Thanks.  So how do i go about installing that linux thing

**Comment by LiquidSchwartz** [comment]
@Dragon863 THere is one issue now, the shell works but i cant get it to boot up properly, the loading symbol doesnt stop

**Comment by Dragon863** [comment]
I don't mean this in a disrespectful way, but it seems you are pretty new to this sort of thing, and given that postmarketos is a recent port with very little driver support I wouldn't recommend that you try it. As for the loading symbol, maybe try to reset the echo with the key combination (can't remember off the top of my head, just google it) and add the device to to your Amazon account again if you want to use the echo as intended.

**Comment by LiquidSchwartz** [comment]
I tried that it just reboots and infinite loading
