### ISSUE TITLE
Unable to root

### ISSUE THREAD

**Issue by isaacloclassranked** [Dragon863/EchoCLI#21]
I had started looking into the echo dot 2 work again; and I got some really promising results; I was actually able to compile rust programs to work on the echo. Unfortunately, I'm experiencing an issue where i'm no longer able to root devices anymore? I keep getting the issue

[20:37:12] Found port = /dev/ttyACM0
[20:37:12] Handshake
[20:37:12] Disable watchdog
ERROR: Serial protocol mismatch
[20:37:17] wrong handshake response, probably in preloader
[20:37:17] Waiting for bootrom

And when printing out the result of a check() method with 'test' and 'gold', I am getting

b''
b'\x00\x01'

**Comment by isaacloclassranked** [comment]
NVM got it working after a few tries, my bad.

**Comment by Dragon863** [comment]
Glad you got it working. If you do get anything interesting running on it (e.g. anything with easy mic/speaker access) please let me know, as I've been unsuccessful in a lot of my attempts. Running rust programs on it sounds really interesting!

**Comment by MaizeShark** [comment]
@isaacloclassranked what was your solution i have the same issue?

**Comment by MaizeShark** [comment]
> @isaacloclassranked what was your solution i have the same issue?

Got it working after a few tries! With the help of ChatGPT, I used fine tweezers to short the large capacitor as shown in the image, and it worked right away.![PXL_20241218_104114574.jpg](https://github.com/user-attachments/assets/bb697e29-f87f-430e-8161-74029c019539)
